site_name: Hearth Encyclopedia
site_url: https://mattlock0.github.io/
site_dir: public
docs_dir: ./wiki

theme:
  name: material
  
  palette:
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    - scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  
  font:
    text: Lora
  
  icon:
    logo: material/shield-moon
    # logo: material/weather-moonset
    # favicon: material/shield-moon

  features:
    - navigation.tabs

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# extra_javascript:
#   - javascripts/katex.js
#   - https://unpkg.com/katex@0/dist/katex.min.js
#   - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

# extra_css:
#   - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  - search
  - roamlinks
  # - tooltipster-links
